### ISSUE TITLE
Bump action to node20

### ISSUE THREAD

**Issue by AlexStormwood** [MariachiBear/get-repo-name-action#67]
Hey, please bump the NodeJS version used in this action up to node20. 

As per this, node16-based actions may stop working any day now: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ 

Just need an edit in the action.yml file.

**Comment by RubenConde** [comment]
Thanks for the information. The changes were made in version `1.3.0` and will be available for release.

**Comment by ruben-conmag** [comment]
Thanks for the information. The changes were made in version `1.3.0` and will be available for release.
